[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
actix-web = "4"
redis = { version = "0.32.0", features = ["tokio-comp"] }

serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
